# Generated by Django 4.2.3 on 2025-07-08 17:00

import base.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tinkoffpayment',
            name='user',
            field=base.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinkoff_payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
