# Generated by Django 4.2.3 on 2025-07-08 17:00

import apps.user.managers
import base.fields
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, help_text='150 символов или меньше. Может содержать только буквы, цифры и символы @/./+/-/_ .', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, db_index=True, default=None, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('first_name', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='Фамилия')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, null=True, verbose_name='Пол')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('os', models.CharField(blank=True, choices=[('Android', 'Android'), ('IOS', 'IOS')], default=None, null=True, verbose_name='Операционная система')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', apps.user.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TempCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False, verbose_name='Подтвержден?')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('code', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Код')),
                ('code_applying', models.IntegerField(default=0, verbose_name='Применений кода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user', base.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Создатель кода')),
            ],
            options={
                'verbose_name': 'Реферальный код',
                'verbose_name_plural': 'Реферальные коды',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Создано')),
                ('points', models.PositiveIntegerField(verbose_name='Баллы')),
                ('charge', models.BooleanField(default=False, verbose_name='Списание?')),
                ('user', base.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Балл',
                'verbose_name_plural': 'Баллы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topik', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('topik_eng', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок на ENG')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('message_eng', models.TextField(blank=True, null=True, verbose_name='Сообщение на ENG')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', base.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=30, verbose_name='Код ссылки')),
                ('enabled', models.BooleanField(default=True, verbose_name='Статус запроса')),
                ('user', base.fields.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forget_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Восстановление пароля',
                'verbose_name_plural': 'Восстановление паролей',
            },
        ),
    ]
