# Generated by Django 4.2.3 on 2025-07-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('name', models.TextField(blank=True, db_index=True, null=True, verbose_name='Название')),
                ('product_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='Айди товара')),
                ('sku', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Поисковый индекс')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='Фото')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('code', models.CharField(db_index=True, max_length=255, verbose_name='Код')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('links', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('cost', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Промо',
                'verbose_name_plural': 'Промо',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.promo', verbose_name='Промо')),
            ],
            options={
                'verbose_name': 'Купленное промо',
                'verbose_name_plural': 'Купленные промо',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
