# Generated by Django 4.2.3 on 2025-07-08 17:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Избранный рецепт',
                'verbose_name_plural': 'Избранные рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('language', models.CharField(choices=[('ENG', 'Английский'), ('RUS', 'Русский')], default='RUS', max_length=20, verbose_name='Язык')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_alcoholic', models.BooleanField(default=False, verbose_name='Алкогольный?')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('language', models.CharField(choices=[('ENG', 'Английский'), ('RUS', 'Русский')], default='RUS', max_length=20, verbose_name='Язык')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название категории')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная?')),
                ('is_alcoholic', models.BooleanField(default=False, verbose_name='Алкогольный?')),
            ],
            options={
                'verbose_name': 'Категория ингредиента',
                'verbose_name_plural': 'Категории ингредиентов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientCategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('language', models.CharField(choices=[('ENG', 'Английский'), ('RUS', 'Русский')], default='RUS', max_length=20, verbose_name='Язык')),
                ('name', models.CharField(max_length=255, verbose_name='Название блока категорий')),
            ],
            options={
                'verbose_name': 'Блок категорий',
                'verbose_name_plural': 'Блоки категорий',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('instruction', models.JSONField(blank=True, null=True, verbose_name='Инструкция')),
                ('isEnabled', models.BooleanField(default=False, verbose_name='Доступен?')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('is_alcoholic', models.BooleanField(default=True, verbose_name='Алкогольный?')),
                ('language', models.CharField(choices=[('ENG', 'Английский'), ('RUS', 'Русский')], default='RUS', max_length=20, verbose_name='Язык')),
                ('moderation_status', models.CharField(choices=[('Draft', 'Черновик'), ('Pending', 'На модерации'), ('Approved', 'Одобрено'), ('Rejected', 'Отклонено'), ('Archive', 'Архив')], default='Draft', max_length=10, verbose_name='Статус модерации')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('video_aws_key', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ключ файла от aws s3 ')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('language', models.CharField(choices=[('ENG', 'Английский'), ('RUS', 'Русский')], default='RUS', max_length=20, verbose_name='Язык')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('history', models.TextField(blank=True, null=True, verbose_name='История')),
                ('how_to_use', models.TextField(blank=True, null=True, verbose_name='Как использовать')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tool_photos/', verbose_name='Фото')),
                ('links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None, verbose_name='Ссылки')),
            ],
            options={
                'verbose_name': 'Инструмент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('type', models.CharField(choices=[('ounce', 'унция'), ('ml', 'мл'), ('gram', 'грамм'), ('piece', 'шт'), ('spoon', 'ложка'), ('cup', 'кружка'), ('tablespoon', 'столовая ложка'), ('teaspoon', 'чайная ложка'), ('slice', 'ломтик'), ('twist', 'твист'), ('cube', 'кубик'), ('sprig', 'веточка'), ('pinch', 'щепотка'), ('spiral', 'спираль'), ('wedge', 'долька'), ('dash', 'дэш'), ('block', 'блок'), ('circle', 'кружок'), ('bottle', 'бутылка')], default='ounce', max_length=30, verbose_name='Мера')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='recipe.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.recipe')),
            ],
            options={
                'verbose_name': 'Ингредиент рецепта',
                'verbose_name_plural': 'Ингредиенты рецепта',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='recipes_tool', to='recipe.tool', verbose_name='Инструменты'),
        ),
    ]
