# Generated by Django implementation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='external_photo_url',
            field=models.URLField(blank=True, help_text='URL for external images (e.g., Google Drive, CDN)', null=True, verbose_name='External Photo URL'),
        ),
    ]
