# Generated by Django 4.2.3 on 2025-08-16 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_move_external_photo_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('language', models.CharField(choices=[('ENG', 'Английский'), ('RUS', 'Русский')], default='RUS', max_length=20, verbose_name='Язык')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название подкатегории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='recipe.ingredientcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория ингредиента',
                'verbose_name_plural': 'Подкатегории ингредиентов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipe.ingredientsubcategory', verbose_name='Подкатегория'),
        ),
        migrations.AddIndex(
            model_name='ingredientsubcategory',
            index=models.Index(fields=['name'], name='recipe_ingr_name_946c7c_idx'),
        ),
    ]
