# Generated by Django 4.2.3 on 2025-08-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_ingredientsubcategory_ingredient_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='IngredientSubcategory',
        ),
    ]
